<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Moneda;

class MonedaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        Moneda::create([ 'moneda' => 'BOB – Boliviano']);
        Moneda::create([ 'moneda' => 'USD - Dólar Americano']);
        Moneda::create([ 'moneda' => 'EUR – Euro']);
        Moneda::create([ 'moneda' => 'AED - Dírham de los Emiratos Árabes Unido']);
        Moneda::create([ 'moneda' => 'AFN – Afghani']);
        Moneda::create([ 'moneda' => 'ALL – Lek']);
        Moneda::create([ 'moneda' => 'AMD - Dram armenio']);
        Moneda::create([ 'moneda' => 'ANG - Florín antillano neerlandés']);
        Moneda::create([ 'moneda' => 'AOA – Kwanza']);
        Moneda::create([ 'moneda' => 'ARS - Peso Argentino']);
        Moneda::create([ 'moneda' => 'AUD - Dólar australiano']);
        Moneda::create([ 'moneda' => 'AWG - Florín arubeño']);
        Moneda::create([ 'moneda' => 'AZN - Manat azerbaiyano']);
        Moneda::create([ 'moneda' => 'BAM - Marco bosnioherzegovino']);
        Moneda::create([ 'moneda' => 'BBD - Dólar de Barbados']);
        Moneda::create([ 'moneda' => 'BDT – Taka']);
        Moneda::create([ 'moneda' => 'BGN - Lev búlgaro']);
        Moneda::create([ 'moneda' => 'BHD - Dinar de Bahrein']);
        Moneda::create([ 'moneda' => 'BIF - Franco Burundi']);
        Moneda::create([ 'moneda' => 'BMD - Dólar de Bermudas']);
        Moneda::create([ 'moneda' => 'BND - Dólar de Brunei']);
        Moneda::create([ 'moneda' => 'BOV – Mvdol']);
        Moneda::create([ 'moneda' => 'BRL - Real Brasileño']);
        Moneda::create([ 'moneda' => 'BSD - Dólar de las Bahamas']);
        Moneda::create([ 'moneda' => 'BTN – Ngultrum']);
        Moneda::create([ 'moneda' => 'BWP – Pula']);
        Moneda::create([ 'moneda' => 'BYR - Rublo bielorruso']);
        Moneda::create([ 'moneda' => 'BZD - Dólar de Belice']);
        Moneda::create([ 'moneda' => 'CAD - Dólar canadiense']);
        Moneda::create([ 'moneda' => 'CDF - Franco congoleño']);
        Moneda::create([ 'moneda' => 'CHE - Euro WIR']);
        Moneda::create([ 'moneda' => 'CHF - Franco suizo']);
        Moneda::create([ 'moneda' => 'CHW - Franco WIR']);
        Moneda::create([ 'moneda' => 'CLF - Unidad de Fomento']);
        Moneda::create([ 'moneda' => 'CLP - Peso chileno']);
        Moneda::create([ 'moneda' => 'CNY – Yuan']);
        Moneda::create([ 'moneda' => 'COP - Peso Colombiano']);
        Moneda::create([ 'moneda' => 'COU - Unidad de Valor Real']);
        Moneda::create([ 'moneda' => 'CRC - Colón costarricense']);
        Moneda::create([ 'moneda' => 'CUC - Peso Convertible']);
        Moneda::create([ 'moneda' => 'CUP - Peso Cubano']);
        Moneda::create([ 'moneda' => 'CVE - Cabo Verde Escudo']);
        Moneda::create([ 'moneda' => 'CZK - Corona checa']);
        Moneda::create([ 'moneda' => 'DJF - Franco de Djibouti']);
        Moneda::create([ 'moneda' => 'DKK - Corona danesa']);
        Moneda::create([ 'moneda' => 'DOP - Peso Dominicano']);
        Moneda::create([ 'moneda' => 'DZD - Dinar argelino']);
        Moneda::create([ 'moneda' => 'EGP - Libra egipcia']);
        Moneda::create([ 'moneda' => 'ERN – Nakfa']);
        Moneda::create([ 'moneda' => 'ETB - Birr etíope']);
        Moneda::create([ 'moneda' => 'FJD - Dólar de Fiji']);
        Moneda::create([ 'moneda' => 'FKP - Libra malvinense']);
        Moneda::create([ 'moneda' => 'GBP - Libra esterlina']);
        Moneda::create([ 'moneda' => 'GEL – Lar']);
        Moneda::create([ 'moneda' => 'GHS - Cedi de Ghana']);
        Moneda::create([ 'moneda' => 'GIP - Libra de Gibraltar']);
        Moneda::create([ 'moneda' => 'GMD – Dalasi']);
        Moneda::create([ 'moneda' => 'GNF - Franco guineano']);
        Moneda::create([ 'moneda' => 'GTQ – Quetzal']);
        Moneda::create([ 'moneda' => 'GYD - Dólar guyanés']);
        Moneda::create([ 'moneda' => 'HKD - Dólar de Hong Kong']);
        Moneda::create([ 'moneda' => 'HNL – Lempira']);
        Moneda::create([ 'moneda' => 'HRK – Kuna']);
        Moneda::create([ 'moneda' => 'HTG – Gourde']);
        Moneda::create([ 'moneda' => 'HUF – Florín']);
        Moneda::create([ 'moneda' => 'IDR – Rupia']);
        Moneda::create([ 'moneda' => 'ILS - Nuevo Shekel Israelí']);
        Moneda::create([ 'moneda' => 'INR - Rupia india']);
        Moneda::create([ 'moneda' => 'IQD - Dinar iraquí']);
        Moneda::create([ 'moneda' => 'IRR - Rial iraní']);
        Moneda::create([ 'moneda' => 'ISK - Corona islandesa']);
        Moneda::create([ 'moneda' => 'JMD - Dólar jamaiquino']);
        Moneda::create([ 'moneda' => 'JOD - Dinar jordano']);
        Moneda::create([ 'moneda' => 'JPY – Yen']);
        Moneda::create([ 'moneda' => 'KES - Chelín keniano']);
        Moneda::create([ 'moneda' => 'KGS – Som']);
        Moneda::create([ 'moneda' => 'KHR – Riel']);
        Moneda::create([ 'moneda' => 'KMF - Franco Comoro']);
        Moneda::create([ 'moneda' => 'KPW - Won norcoreano']);
        Moneda::create([ 'moneda' => 'KRW – Won']);
        Moneda::create([ 'moneda' => 'KWD - Dinar kuwaití']);
        Moneda::create([ 'moneda' => 'KYD - Dólar de las Islas Caimán']);
        Moneda::create([ 'moneda' => 'KZT – Tenge']);
        Moneda::create([ 'moneda' => 'LAK – Kip']);
        Moneda::create([ 'moneda' => 'LBP - Libra libanesa']);
        Moneda::create([ 'moneda' => 'LKR - Rupia de Sri Lanka']);
        Moneda::create([ 'moneda' => 'LRD - Dólar liberiano']);
        Moneda::create([ 'moneda' => 'LSL – Loti']);
        Moneda::create([ 'moneda' => 'LYD - Dinar libio']);
        Moneda::create([ 'moneda' => 'MAD - Dirham marroquí']);
        Moneda::create([ 'moneda' => 'MDL - Leu moldavo']);
        Moneda::create([ 'moneda' => 'MGA - Ariary malgache']);
        Moneda::create([ 'moneda' => 'MKD – Denar']);
        Moneda::create([ 'moneda' => 'MMK – Kyat']);
        Moneda::create([ 'moneda' => 'MNT – Tugrik']);
        Moneda::create([ 'moneda' => 'MOP – Pataca']);
        Moneda::create([ 'moneda' => 'MRO – Ouguiya']);
        Moneda::create([ 'moneda' => 'MUR - Rupia de Mauricio']);
        Moneda::create([ 'moneda' => 'MVR – Rufiyaa']);
        Moneda::create([ 'moneda' => 'MWK – Kwacha']);
        Moneda::create([ 'moneda' => 'MXN - Peso Mexicano']);
        Moneda::create([ 'moneda' => 'MXV - Unidad de Inversion Mexicana (UDI)']);
        Moneda::create([ 'moneda' => 'MYR - Ringgit malayo']);
        Moneda::create([ 'moneda' => 'MZN - Metical mozambiqueño']);
        Moneda::create([ 'moneda' => 'NAD - Dólar de Namibia']);
        Moneda::create([ 'moneda' => 'NGN – Naira']);
        Moneda::create([ 'moneda' => 'NIO - Cordoba Oro']);
        Moneda::create([ 'moneda' => 'NOK - Corona noruega']);
        Moneda::create([ 'moneda' => 'NPR - Rupia nepalí']);
        Moneda::create([ 'moneda' => 'NZD - Dólar neozelandés']);
        Moneda::create([ 'moneda' => 'OMR - Rial omaní']);
        Moneda::create([ 'moneda' => 'PAB – Balboa']);
        Moneda::create([ 'moneda' => 'PEN - Nuevo Sol']);
        Moneda::create([ 'moneda' => 'PGK – Kina']);
        Moneda::create([ 'moneda' => 'PHP - Peso filipino']);
        Moneda::create([ 'moneda' => 'PKR - Rupia pakistaní']);
        Moneda::create([ 'moneda' => 'PLN – Zloty']);
        Moneda::create([ 'moneda' => 'PYG – Guaraní']);
        Moneda::create([ 'moneda' => 'QAR - Riyal catarí']);
        Moneda::create([ 'moneda' => 'RON - Leu rumano']);
        Moneda::create([ 'moneda' => 'RSD - Dinar serbio']);
        Moneda::create([ 'moneda' => 'RUB - Rublo ruso']);
        Moneda::create([ 'moneda' => 'RWF - Franco ruandés']);
        Moneda::create([ 'moneda' => 'SAR - Riyal saudí']);
        Moneda::create([ 'moneda' => 'SBD - Dólar de las Islas Salomón']);
        Moneda::create([ 'moneda' => 'SCR - Rupia seychelense']);
        Moneda::create([ 'moneda' => 'SDG - Libra sudanesa']);
        Moneda::create([ 'moneda' => 'SEK - Corona sueca']);
        Moneda::create([ 'moneda' => 'SGD - Dolar de Singapur']);
        Moneda::create([ 'moneda' => 'SHP - Libra de Santa Helena']);
        Moneda::create([ 'moneda' => 'SLL – Leone']);
        Moneda::create([ 'moneda' => 'SOS - Chelín somalí']);
        Moneda::create([ 'moneda' => 'SRD - Dólar surinamés']);
        Moneda::create([ 'moneda' => 'SSP - Libra sursudanesa']);
        Moneda::create([ 'moneda' => 'STD – Dobra']);
        Moneda::create([ 'moneda' => 'SVC – Colón']);
        Moneda::create([ 'moneda' => 'SYP - Libra Siria']);
        Moneda::create([ 'moneda' => 'SZL – Lilangeni']);
        Moneda::create([ 'moneda' => 'THB – Baht']);
        Moneda::create([ 'moneda' => 'TJS – Somoni']);
        Moneda::create([ 'moneda' => 'TMT - Manat turcomano']);
        Moneda::create([ 'moneda' => 'TND - Dinar tunecino']);
        Moneda::create([ 'moneda' => 'TOP - Pa’anga']);
        Moneda::create([ 'moneda' => 'TRY - Lira turca']);
        Moneda::create([ 'moneda' => 'TTD - Dólar trinitense']);
        Moneda::create([ 'moneda' => 'TWD - Nuevo dólar taiwanés']);
        Moneda::create([ 'moneda' => 'TZS - Chelín tanzano']);
        Moneda::create([ 'moneda' => 'UAH – Hryvnia']);
        Moneda::create([ 'moneda' => 'UGX - Chelín ugandés']);
        Moneda::create([ 'moneda' => 'USD - Dólar estadounidense']);
        Moneda::create([ 'moneda' => 'USN - Dólar Americano (Next day)']);
        Moneda::create([ 'moneda' => 'UYI - Uruguay Peso en Unidades Indexadas']);
        Moneda::create([ 'moneda' => 'UYU - Peso Uruguayo']);
        Moneda::create([ 'moneda' => 'UZS - Som uzbeko']);
        Moneda::create([ 'moneda' => 'VEF – Bolívar']);
        Moneda::create([ 'moneda' => 'VND – Dong']);
        Moneda::create([ 'moneda' => 'VUV – Vatu']);
        Moneda::create([ 'moneda' => 'WST – Tala']);
        Moneda::create([ 'moneda' => 'XAF - Franco CFA BEAC']);
        Moneda::create([ 'moneda' => 'XCD - Dólar del Caribe Oriental']);
        Moneda::create([ 'moneda' => 'XDR - SDR (Derechos Especiales de Giro)']);
        Moneda::create([ 'moneda' => 'XOF - Franco CFA BCEAO']);
        Moneda::create([ 'moneda' => 'XPF - CFP Franc']);
        Moneda::create([ 'moneda' => 'XPF - Franco CFP']);
        Moneda::create([ 'moneda' => 'XSU – Sucre']);
        Moneda::create([ 'moneda' => 'XUA - Unidad de cuenta del BAD']);
        Moneda::create([ 'moneda' => 'YER - Rial yemení']);
        Moneda::create([ 'moneda' => 'ZAR – Rand']);
        Moneda::create([ 'moneda' => 'ZMW - Kwacha zambiano']);
        Moneda::create([ 'moneda' => 'ZWL - Dólar zimbabuense']);
    }
}
